### PR TITLE
Taking a look at the theme

### PR DESCRIPTION
**Pull request by avahoffman**
Worked on the theming for GDSCN a bit - the green for the main headers was kind of light and I think this is more readable.

Appreciate any additional thoughts @KatherineCox @ehumph ! Here's a preview (won't show up on the link below since it uses the AnVIL theme by default)

image

### CODE REVIEW

**Comment by KatherineCox** [comment]
@avahoffman Nice!  It's been on my wishlist to do something like this.  Looks great!
My only comment is, instead of changing the css colors in place, I would override them at the bottom of the file, so that it's easier to maintain.

**Comment by avahoffman** [comment]
@KatherineCox I am working on a possible solution here: https://github.com/jhudsl/ottrpal/pull/115 FYI! The goal is that one would be able to use multiple css files in both the regular and ToC-less versions.

**Comment by ehumph** [comment]
I am a little worried that the black and green color scheme won't work for people who are red-green colorblind. It might not be a problem - the green is just going to be indistinguishable from the black for some people - though it's nice to have the different colors on the side menu.

**Comment by avahoffman** [comment]
@ehumph thanks for raising this. I think the only changes are from dark blue --> dark green and light blue --> light green. So they should hopefully still be distinguishable.

Not sure if this is 100% accurate, but here's a simulation of no green color vis:
image
monochrome:
image

Think this will work?

**Review by KatherineCox — APPROVED** [review]
Looks good!

**Comment by KatherineCox** [comment]
> @KatherineCox I am working on a possible solution here: [jhudsl/ottrpal#115](https://github.com/jhudsl/ottrpal/pull/115) FYI! The goal is that one would be able to use multiple css files in both the regular and ToC-less versions.

Awesome!  That would be great, to be able to split things out into separate files.

**Comment by ehumph** [comment]
Looks good to me!

**Review by ehumph — APPROVED** [review]

**Pull request merged**
