### PR TITLE
"special_workflow" config_automation.yml option

### PR DESCRIPTION
**Pull request by cansavvy**
#### What changes are being implemented in this Pull Request?
This is in response to a BaseCamp conversation. 

How do we have other workflows that need to be run added into the pull_request.yml without accidentally overwriting them in sync PRs? 

We can try to specify one in config_automation.yml (at least that's what I'm trying to do here. Let's see 🤞)

### CODE REVIEW

**Comment by cansavvy** [comment]
I'm really close on this. 
```
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/AnVIL_Template/AnVIL_Template/.github/workflows/custom-workflow.yml'. Did you forget to run actions/checkout before running your local action?
```
This error is saying that it can't find the file, but I've done multiple tests to show that the file is there and where it says. 

But as far as I can tell, this is following what the documentation says: https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow 

So I'm a bit stumped. I can look at it again later, unless @avahoffman wants to take a whack at it.

**Comment by cansavvy** [comment]
Ah, I see. It needs a metadata file: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

I'll whip one up.

**Comment by avahoffman** [comment]
@cansavvy are you still working on this?

**Comment by cansavvy** [comment]
> @cansavvy are you still working on this? I like the direction this is headed. If you get to a stopping point or are stuck I'm happy to jump in (but don't want to duplicate too much effort) 🙂 

No worries! Yea I'll be returning to it later this week but if you want to take a whack at it in the meantime, that is great!

**Comment by avahoffman** [comment]
@cansavvy I think I have things working.. but for some reason now the access token isnt working.

One thing that might need rethinking is the custom workflow toggle. As is, it's necessary for render-preview. So if the custom-workflow toggle is off, the preview doesn't get rendered regardless of what its toggle is set to. 

Maybe what I'm trying to say is that the custom workflow should just be a dummy workflow for OTTR, but customized for AnVIL. Thoughts?

**Comment by cansavvy** [comment]
> Maybe what I'm trying to say is that the custom workflow should just be a dummy workflow for OTTR, but customized for AnVIL. Thoughts?

I was writing this with mainly OTTR general purposes in mind, but you should definitely customize it for this anvil template for what you need. I'll bring over the useful things to the main OTTR template after we've developed it here.

**Comment by avahoffman** [comment]
> > Maybe what I'm trying to say is that the custom workflow should just be a dummy workflow for OTTR, but customized for AnVIL. Thoughts?
> 
> I was writing this with mainly OTTR general purposes in mind, but you should definitely customize it for this anvil template for what you need. I'll bring over the useful things to the main OTTR template after we've developed it here.

@cansavvy Totally. I'm not doing a good job explaining 😛 . I'm thinking OTTR would:

- have something extremely basic in the custom workflow file. 
- ignore the custom workflow file downstream. That way no OTTR updates overwrite it.
- not have a custom workflow toggle. It will always be run.

Happy to discuss if helpful!!

**Comment by cansavvy** [comment]
> - have something extremely basic in the custom workflow file. 
> 
> - ignore the custom workflow file downstream. That way no OTTR updates overwrite it.
> 
> - not have a custom workflow toggle. It will always be run.
> 

This sounds like a good plan.

**Pull request merged**
