### PR TITLE
Update update-enrollment.md

### PR DESCRIPTION
**Pull request by KatherineCox**
Modify the `update-enrollment` automatic issue with instructions to subscribe to AnVIL_Template in addition to OTTR_Template

...now to go make the corresponding wiki page :)

### CODE REVIEW

**Comment by avahoffman** [comment]
I wonder if it makes sense to have downstream repos just receive updates from AnVIL_Template? AnVIL_Template will recieve updates from OTTR_Template so is there a reason to do it twice?

**Comment by avahoffman** [comment]
I guess we could always change the policy! I'm just imaging a frustrating scenario where OTTR_Template syncs overwrite the AnVIL_Template syncs. We always want AnVIL_Template to take precedence, right? But I definitely see your concern about maintaining AnVIL_Template and ensuring there are prompt updates.

**Comment by KatherineCox** [comment]
> I guess we could always change the policy! I'm just imaging a frustrating scenario where OTTR_Template syncs overwrite the AnVIL_Template syncs. We always want AnVIL_Template to take precedence, right?

I think this is avoidable if we make a new group in the OTTR sync.yml (#53) for AnVIL repos, which subscribes to fewer files than a normal OTTR course - leaving out everything we'd rather they get from AnVIL_Template.

And yeah, if it turns out to be problematic, we can definitely switch!

> My only other comment is that maybe we want to use AnVIL specific screenshots for the wiki 🙂 Looks good otherwise!

Agreed! #66

Unless you find the dangling PR annoying, I think I'll leave this open while you and Candace are working out the workflow reorganization?  If workflows end up pointing back to OTTR anyway (à la https://github.com/jhudsl/OTTR_Template/issues/502), then updates are less of a concern, and maybe it make more sense to subscribe just to AnVIL.

**Comment by avahoffman** [comment]
@KatherineCox I'm okay leaving this open for now, given it's documentation. Shouldn't be a problem :)

**Comment by avahoffman** [comment]
@KatherineCox are we okay closing this? I think we should just have folks subscribe to ANVIL_template. It will get a little complicated to have both because the custom workflow appears in both pull-request and render-all workflows. 

Does that sound okay? I can update the automatic issue accordingly.

**Comment by avahoffman** [comment]
Apologies for the flurry of comments - I've added a PR #125 which fits with a OTTR -> ANVIL_TEMPLATE -> downstream model.

**Comment by KatherineCox** [comment]
Yes, I agree, with all the customizations to the workflows it makes more sense for downstream repos to subscribe only to `AnVIL_Template`, not OTTR.

**Pull request closed without merging**
