### PR TITLE
Attempt at student config

### PR DESCRIPTION
**Pull request by avahoffman**
Playing around with solutions for #176 

Perhaps not the most elegant solution but this one creates a student guide based off of separate `_bookdown.yml` and `_output.yml` files in the student-guide directory.

### CODE REVIEW

**Comment by avahoffman** [comment]
> The TOC seems broken

Do you mean in the docx?

**Comment by KatherineCox** [comment]
> > The TOC seems broken
> 
> Do you mean in the docx?

Yeah, in the docx.  When I download and open it on my Mac (using Word), the TOC is empty.

**Comment by avahoffman** [comment]
@KatherineCox You have to select "Yes" here. Perhaps that should go in the instructions?

Screen Shot 2022-12-07 at 10 42 53 AM

**Comment by KatherineCox** [comment]
Oh 🤦, I didn't even think about that, you're right, it works just fine if I say yes.  Yeah, that'd be good to add to the instructions.  My general assumption is that whatever Word wants to do to "fix" a file will probably break it, haha, especially if it came from some non-Word source, so I default to clicking "No".

**Review by KatherineCox — APPROVED** [review]

**Pull request merged**
