### PR TITLE
Updating the files that need to be considered with `sync.yml`

### PR DESCRIPTION
**Pull request by avahoffman**
Updating the files that we want to push out to sync.

I think all of these make sense. Not sure if we need `ottr-fy.R`?

**IMPORTANT**:

`config_automation.yml` needs to be updated to use the updated docker image:
```
rendering-docker-image: 'jhudsl/base_ottr:main'
```

### CODE REVIEW

**Comment by KatherineCox** [comment]
So, the reason I had asset files and subdirectories listed out individually instead of just syncing the whole `assets` directory was in case any downstream repos decided to put some of their own book-specific assets in the `assets` directory.  I didn't want to clobber them or make PRs harder.  Not sure how often that'll happen in reality?

**Comment by avahoffman** [comment]
The only one I found was the gdscn word doc template. Happy to change it back.

**Review by KatherineCox — APPROVED** [review]
Eh, if it's not actually causing problems then I'm okay with syncing the whole directory.  We can switch back later if it becomes a problem.

I guess we're unlikely to have many book-specific assets if our images are all being pulled in from Google slides.

**Comment by KatherineCox** [comment]
Haha, I'm too slow with my comments :)  Either way is fine with me.

**Comment by avahoffman** [comment]
hehe! I think it's probably the most cautious solution. I'm on board :)

**Comment by KatherineCox** [comment]
Closes #196 (does the this work if I add it after the PR has been merged?)

**Pull request merged**
