### PR TITLE
Testing out the newly implemented multi-css capability

### PR DESCRIPTION
**Pull request by avahoffman**
in response to https://github.com/jhudsl/ottrpal/pull/115

@KatherineCox @cansavvy I think this is working as expected!

Let's see how this one goes before 
- modifying the file structure of GDSCN, etc.
- pushing the docker image to `latest`

I am about 80% sure the following chunk is okay to take out, due to the restored file path. If I'm wrong, I will fix :)

```
/* fix the image urls since our AnVIL style is in a different location */
/* images paths are relative to the CSS file */

div.notice{
  background-image: url("../box_images/note.png");
}

div.warning{
  background-image: url("../box_images/warning.png");
}

div.github{
  background-image: url("../box_images/github.png");
}

div.dictionary{
  background-image: url("../box_images/dictionary.png");
}

div.reflection{
  background-image: url("../box_images/thinking_face.png");
}
```

### CODE REVIEW

**Comment by avahoffman** [comment]
She works! Added an "ugly" color mod.

Regular:
Screen Shot 2023-03-09 at 5 50 30 PM
No ToC:
Screen Shot 2023-03-09 at 5 50 45 PM

**Comment by KatherineCox** [comment]
I'll take a look at everything when I'm at my computer, but yes, you should be good to drop those file paths 👍. I had to add them when I moved the style file down into the AnVIL assets directory, since paths are relative to the location of the css file.

Related, we'll want to update the sync.yml file in OTTR_Template so that the OTTR style.css file is syncing to the correct AnVIL_Template file.

Yay! This is exciting! Awesome work!!!

**Review by cansavvy — APPROVED** [review]
This makes sense to me! As long as it looks like it is working to you. One last step we’ll need to do is push the latest `base_ottr` docker image to have the `main` tag if we have confirmed the ottrpal updates are working as expected.

**Comment by avahoffman** [comment]
> This makes sense to me! As long as it looks like it is working to you. One last step we’ll need to do is push the latest `base_ottr` docker image to have the `main` tag if we have confirmed the ottrpal updates are working as expected.

Yes definitely. Would you rather (1) wait a bit to see if this causes any trouble here, or (2) just push now with the option to revert if need be? I am ok yolo'ing the image if you are!

**Comment by avahoffman** [comment]
Well poop - needed to update `render-all.yml` as well 😛 : #199

**Pull request merged**
