### PR TITLE
Adding some more formatting for Hutch-created courses

### PR DESCRIPTION
**Pull request by avahoffman**
Cleaning up the Hutch-themed anvil content.

You can see it in action here: https://hutchdatascience.org/AnVIL_Book_Epigenetics_Intro/

image

### CODE REVIEW

**Comment by KatherineCox** [comment]
@avahoffman Is the plan for all the Hutch courses/books to collect feedback through the same Google Form?

**Comment by KatherineCox** [comment]
also related to this PR, it looks like the Hutch logo in `main` has gone missing, so update that link as well?

https://github.com/jhudsl/AnVIL_Template/blob/11630f2a0455f3079d98b39ddd170b895a2d6b67/_output.yml#L15

**Comment by avahoffman** [comment]
> @avahoffman Is the plan for all the Hutch courses/books to collect feedback through the same Google Form?

I think that makes the most sense (for now). That way we don't forget to add a feedback method.

**Comment by avahoffman** [comment]
> also related to this PR, it looks like the Hutch logo in the root `output.yml` has gone missing, so update that link as well?

Thanks!

**Review by KatherineCox — APPROVED** [review]
> I think that makes the most sense (for now). That way we don't forget to add a feedback method.

Sounds reasonable to me!

Might want to
- Update the feedback automatic issue https://github.com/jhudsl/AnVIL_Template/blob/main/.github/automatic-issues/add-feedback-method.md
- Either within the automatic issue or on the wiki give some brief instructions/info (like, add your course to the list of options on the form)

Regardless, changes to the book look good 👍

**Pull request merged**
