### PR TITLE
🔄 Synced file(s) with jhudsl/OTTR_Template

### PR DESCRIPTION
**Pull request by cansavvy**
Synced local file(s) with [jhudsl/OTTR_Template](https://github.com/jhudsl/OTTR_Template).

<details>
<summary>Changed files</summary>
<ul>
<li>Synced local directory <code>.github/workflows/</code> with remote directory <code>.github/workflows/</code></li><li>Synced local  <code>assets/AnVIL_style/style.css</code> with remote  <code>assets/style.css</code></li>
</ul>
</details>

---

This PR was created automatically by the [repo-file-sync-action](https://github.com/BetaHuhn/repo-file-sync-action) workflow run [#4304532444](https://github.com/jhudsl/OTTR_Template/actions/runs/4304532444)

### CODE REVIEW

**Comment by KatherineCox** [comment]
@avahoffman I added back the css that got removed, but I moved it to the bottom so all the differences from OTTR are grouped together.  Partly for easier maintenance now, partly in the hope that someday https://github.com/jhudsl/OTTR_Template/issues/536 will get fixed and then it's easy to see what css to move to a separate file.

**Comment by cansavvy** [comment]
We will have more people power soon with Howard joining us! So hopefully that can get addressed.

**Comment by KatherineCox** [comment]
@avahoffman would it be easiest to just close this PR and run a new sync?

**Comment by avahoffman** [comment]
@KatherineCox probably! Happy to do that.

**Pull request closed without merging**
